// Code generated by "stringer -type=Instr"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nop-0]
	_ = x[Not-1]
	_ = x[Eq-2]
	_ = x[Ne-3]
	_ = x[Gt-4]
	_ = x[Ge-5]
	_ = x[Lt-6]
	_ = x[Le-7]
	_ = x[And-8]
	_ = x[Or-9]
	_ = x[Add-10]
	_ = x[Sub-11]
	_ = x[Mul-12]
	_ = x[Div-13]
	_ = x[LdConst-14]
	_ = x[LdStack-15]
	_ = x[StStack-16]
	_ = x[LdMember-17]
	_ = x[StMember-18]
	_ = x[LdVar-19]
	_ = x[StVar-20]
	_ = x[Call-21]
	_ = x[Conv-22]
	_ = x[Pack-23]
	_ = x[Unpack-24]
	_ = x[Ret-25]
}

const _Instr_name = "NopNotEqNeGtGeLtLeAndOrAddSubMulDivLdConstLdStackStStackLdMemberStMemberLdVarStVarCallConvPackUnpackRet"

var _Instr_index = [...]uint8{0, 3, 6, 8, 10, 12, 14, 16, 18, 21, 23, 26, 29, 32, 35, 42, 49, 56, 64, 72, 77, 82, 86, 90, 94, 100, 103}

func (i Instr) String() string {
	if i >= Instr(len(_Instr_index)-1) {
		return "Instr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Instr_name[_Instr_index[i]:_Instr_index[i+1]]
}
