// Code generated by "stringer -type=OpType"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Any-0]
	_ = x[Str-1]
	_ = x[Int64-2]
	_ = x[Int-3]
	_ = x[Bool-4]
}

const _OpType_name = "AnyStrInt64IntBool"

var _OpType_index = [...]uint8{0, 3, 6, 11, 14, 18}

func (i OpType) String() string {
	if i >= OpType(len(_OpType_index)-1) {
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
